steps:

- id: 'Installing npm'
  name: 'node:16'    #image
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      npm install

- id: 'Installing yarn'
  name: 'node:16'  
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      yarn global add add typescript
  
- id: 'Build api'
  name: 'node:16'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      yarn build

#- id: 'Start api'
#  name: 'node:16'
#  entrypoint: 'bash'
#  args:
#    - '-c'
#    - |
#      yarn start 

- id: 'Depoy to App Engine'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1600s'

 