steps:

- id: 'Installing npm'
  name: 'node:16'    #image
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      npm install

- id: 'Installing yarn'
  name: 'node:16'  
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      yarn global add add typescript
      echo Node version...
      node -v
      
  
- id: 'Build api'
  name: 'node:16'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo Build started on `date`
      yarn run build
      echo Build completed

- id: 'post_build'
  name: 'node:16'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo Build completed on `date`
      cp -R node_modules/ dist/node_modules
      cp -R assets/ dist/assets

- id: 'Depoy to App Engine'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
  volumes:
    - name: 'dist/'
      path: 'dist/**/*'

    - name: 'package.json'
      path: 'package.json'

    - name: 'package-lock.json'
      path: 'package-lock.json'

    - name: 'node_modules'
      path: 'node_modules/**/*'

    - name: 'assets'
      path: 'assets/**/*'
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1600s'

 